### ISSUE TITLE
SuperSocket.ClientEngine is throwing SocketException in unsafe thread from the pool

### ISSUE THREAD

**Issue by JerYme** [kerryjiang/SuperSocket.ClientEngine#63]
I committed a fix for this particular case, fee free to discard it and fix it in a better way.

This error, obviously, bring any application to crash immediately.

See below the full stacktrace:
UnhandledException System.Net.Sockets.SocketException (0x80004005): The system detected an invalid pointer address in attempting to use a pointer argument in a call
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at SuperSocket.ClientEngine.ConnectAsyncExtension.OnGetHostAddresses(IAsyncResult result)
at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
at System.Net.ContextAwareResult.CompleteCallback(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Net.ContextAwareResult.Complete(IntPtr userToken)
at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
at System.Net.Dns.ResolveCallback(Object context)
at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by kerryjiang** [comment]
OK, I'll review it tonight.

**Comment by kerryjiang** [comment]
I made a change to improve the exception handling.
Could you try it and check if it fix your issue?

**Comment by kerryjiang** [comment]
@JerYme Hello, does this work for you?
